name: Formatting Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install typstyle
        run: cargo install typstyle

      - name: Show typstyle version
        run: typstyle --version

      - name: Run formatting check
        shell: bash
        run: |
          chmod +x ./scripts/format.sh
          ./scripts/format.sh -c
